name: flutter_native_image
description: A new flutter plugin project.
version: 0.0.3
author: btastic <bkonsem@gmail.com>
homepage: https://github.com/btastic

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: '>=1.0.0 <2.1.0'
  flutter: ">=0.1.0 <=0.8.1-pre.7"
  
flutter:
  plugin:
    androidPackage: com.example.flutternativeimage
    pluginClass: FlutterNativeImagePlugin
